"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2020 Adap GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Code:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Code.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OK: _Code.ValueType  # 0
    GET_PROPERTIES_NOT_IMPLEMENTED: _Code.ValueType  # 1
    GET_PARAMETERS_NOT_IMPLEMENTED: _Code.ValueType  # 2
    FIT_NOT_IMPLEMENTED: _Code.ValueType  # 3
    EVALUATE_NOT_IMPLEMENTED: _Code.ValueType  # 4

class Code(_Code, metaclass=_CodeEnumTypeWrapper): ...

OK: Code.ValueType  # 0
GET_PROPERTIES_NOT_IMPLEMENTED: Code.ValueType  # 1
GET_PARAMETERS_NOT_IMPLEMENTED: Code.ValueType  # 2
FIT_NOT_IMPLEMENTED: Code.ValueType  # 3
EVALUATE_NOT_IMPLEMENTED: Code.ValueType  # 4
global___Code = Code

class _Reason:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Reason.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _Reason.ValueType  # 0
    RECONNECT: _Reason.ValueType  # 1
    POWER_DISCONNECTED: _Reason.ValueType  # 2
    WIFI_UNAVAILABLE: _Reason.ValueType  # 3
    ACK: _Reason.ValueType  # 4

class Reason(_Reason, metaclass=_ReasonEnumTypeWrapper): ...

UNKNOWN: Reason.ValueType  # 0
RECONNECT: Reason.ValueType  # 1
POWER_DISCONNECTED: Reason.ValueType  # 2
WIFI_UNAVAILABLE: Reason.ValueType  # 3
ACK: Reason.ValueType  # 4
global___Reason = Reason

@typing_extensions.final
class Status(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    code: global___Code.ValueType
    message: builtins.str
    def __init__(
        self,
        *,
        code: global___Code.ValueType = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code", b"code", "message", b"message"]) -> None: ...

global___Status = Status

@typing_extensions.final
class Parameters(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TENSORS_FIELD_NUMBER: builtins.int
    TENSOR_TYPE_FIELD_NUMBER: builtins.int
    @property
    def tensors(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    tensor_type: builtins.str
    def __init__(
        self,
        *,
        tensors: collections.abc.Iterable[builtins.bytes] | None = ...,
        tensor_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["tensor_type", b"tensor_type", "tensors", b"tensors"]) -> None: ...

global___Parameters = Parameters

@typing_extensions.final
class ServerMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ReconnectIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SECONDS_FIELD_NUMBER: builtins.int
        seconds: builtins.int
        def __init__(
            self,
            *,
            seconds: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["seconds", b"seconds"]) -> None: ...

    @typing_extensions.final
    class GetPropertiesIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class ConfigEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        CONFIG_FIELD_NUMBER: builtins.int
        @property
        def config(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            config: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["config", b"config"]) -> None: ...

    @typing_extensions.final
    class GetParametersIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class ConfigEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        CONFIG_FIELD_NUMBER: builtins.int
        @property
        def config(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            config: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["config", b"config"]) -> None: ...

    @typing_extensions.final
    class FitIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class ConfigEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        PARAMETERS_FIELD_NUMBER: builtins.int
        CONFIG_FIELD_NUMBER: builtins.int
        @property
        def parameters(self) -> global___Parameters: ...
        @property
        def config(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            parameters: global___Parameters | None = ...,
            config: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["parameters", b"parameters"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["config", b"config", "parameters", b"parameters"]) -> None: ...

    @typing_extensions.final
    class EvaluateIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class ConfigEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        PARAMETERS_FIELD_NUMBER: builtins.int
        CONFIG_FIELD_NUMBER: builtins.int
        @property
        def parameters(self) -> global___Parameters: ...
        @property
        def config(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            parameters: global___Parameters | None = ...,
            config: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["parameters", b"parameters"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["config", b"config", "parameters", b"parameters"]) -> None: ...

    @typing_extensions.final
    class SecAggMsg(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class SetupParam(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            @typing_extensions.final
            class SecAggParamDictEntry(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                KEY_FIELD_NUMBER: builtins.int
                VALUE_FIELD_NUMBER: builtins.int
                key: builtins.str
                @property
                def value(self) -> global___Scalar: ...
                def __init__(
                    self,
                    *,
                    key: builtins.str = ...,
                    value: global___Scalar | None = ...,
                ) -> None: ...
                def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
                def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

            SEC_AGG_PARAM_DICT_FIELD_NUMBER: builtins.int
            @property
            def sec_agg_param_dict(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
            def __init__(
                self,
                *,
                sec_agg_param_dict: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["sec_agg_param_dict", b"sec_agg_param_dict"]) -> None: ...

        @typing_extensions.final
        class AskKeys(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            @typing_extensions.final
            class ConfigEntry(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                KEY_FIELD_NUMBER: builtins.int
                VALUE_FIELD_NUMBER: builtins.int
                key: builtins.str
                @property
                def value(self) -> global___Scalar: ...
                def __init__(
                    self,
                    *,
                    key: builtins.str = ...,
                    value: global___Scalar | None = ...,
                ) -> None: ...
                def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
                def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

            CONFIG_FIELD_NUMBER: builtins.int
            @property
            def config(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
            def __init__(
                self,
                *,
                config: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["config", b"config"]) -> None: ...

        @typing_extensions.final
        class ShareKeys(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            @typing_extensions.final
            class KeysPair(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                PK1_FIELD_NUMBER: builtins.int
                PK2_FIELD_NUMBER: builtins.int
                pk1: builtins.bytes
                pk2: builtins.bytes
                def __init__(
                    self,
                    *,
                    pk1: builtins.bytes = ...,
                    pk2: builtins.bytes = ...,
                ) -> None: ...
                def ClearField(self, field_name: typing_extensions.Literal["pk1", b"pk1", "pk2", b"pk2"]) -> None: ...

            @typing_extensions.final
            class PublicKeysDictEntry(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                KEY_FIELD_NUMBER: builtins.int
                VALUE_FIELD_NUMBER: builtins.int
                key: builtins.int
                @property
                def value(self) -> global___ServerMessage.SecAggMsg.ShareKeys.KeysPair: ...
                def __init__(
                    self,
                    *,
                    key: builtins.int = ...,
                    value: global___ServerMessage.SecAggMsg.ShareKeys.KeysPair | None = ...,
                ) -> None: ...
                def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
                def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

            PUBLIC_KEYS_DICT_FIELD_NUMBER: builtins.int
            @property
            def public_keys_dict(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___ServerMessage.SecAggMsg.ShareKeys.KeysPair]: ...
            def __init__(
                self,
                *,
                public_keys_dict: collections.abc.Mapping[builtins.int, global___ServerMessage.SecAggMsg.ShareKeys.KeysPair] | None = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["public_keys_dict", b"public_keys_dict"]) -> None: ...

        @typing_extensions.final
        class AskVectors(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            @typing_extensions.final
            class Packet(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                SOURCE_FIELD_NUMBER: builtins.int
                DESTINATION_FIELD_NUMBER: builtins.int
                CIPHERTEXT_FIELD_NUMBER: builtins.int
                source: builtins.int
                destination: builtins.int
                ciphertext: builtins.bytes
                def __init__(
                    self,
                    *,
                    source: builtins.int = ...,
                    destination: builtins.int = ...,
                    ciphertext: builtins.bytes = ...,
                ) -> None: ...
                def ClearField(self, field_name: typing_extensions.Literal["ciphertext", b"ciphertext", "destination", b"destination", "source", b"source"]) -> None: ...

            @typing_extensions.final
            class FitIns(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                @typing_extensions.final
                class ConfigEntry(google.protobuf.message.Message):
                    DESCRIPTOR: google.protobuf.descriptor.Descriptor

                    KEY_FIELD_NUMBER: builtins.int
                    VALUE_FIELD_NUMBER: builtins.int
                    key: builtins.str
                    @property
                    def value(self) -> global___Scalar: ...
                    def __init__(
                        self,
                        *,
                        key: builtins.str = ...,
                        value: global___Scalar | None = ...,
                    ) -> None: ...
                    def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
                    def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

                PARAMETERS_FIELD_NUMBER: builtins.int
                CONFIG_FIELD_NUMBER: builtins.int
                @property
                def parameters(self) -> global___Parameters: ...
                @property
                def config(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
                def __init__(
                    self,
                    *,
                    parameters: global___Parameters | None = ...,
                    config: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
                ) -> None: ...
                def HasField(self, field_name: typing_extensions.Literal["parameters", b"parameters"]) -> builtins.bool: ...
                def ClearField(self, field_name: typing_extensions.Literal["config", b"config", "parameters", b"parameters"]) -> None: ...

            PACKET_LIST_FIELD_NUMBER: builtins.int
            FIT_INS_FIELD_NUMBER: builtins.int
            @property
            def packet_list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ServerMessage.SecAggMsg.AskVectors.Packet]: ...
            @property
            def fit_ins(self) -> global___ServerMessage.SecAggMsg.AskVectors.FitIns: ...
            def __init__(
                self,
                *,
                packet_list: collections.abc.Iterable[global___ServerMessage.SecAggMsg.AskVectors.Packet] | None = ...,
                fit_ins: global___ServerMessage.SecAggMsg.AskVectors.FitIns | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["fit_ins", b"fit_ins"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["fit_ins", b"fit_ins", "packet_list", b"packet_list"]) -> None: ...

        @typing_extensions.final
        class UnmaskVectors(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            AVAILABLE_CLIENTS_FIELD_NUMBER: builtins.int
            DROPOUT_CLIENTS_FIELD_NUMBER: builtins.int
            @property
            def available_clients(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
            @property
            def dropout_clients(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
            def __init__(
                self,
                *,
                available_clients: collections.abc.Iterable[builtins.int] | None = ...,
                dropout_clients: collections.abc.Iterable[builtins.int] | None = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["available_clients", b"available_clients", "dropout_clients", b"dropout_clients"]) -> None: ...

        SETUP_PARAM_FIELD_NUMBER: builtins.int
        ASK_KEYS_FIELD_NUMBER: builtins.int
        SHARE_KEYS_FIELD_NUMBER: builtins.int
        ASK_VECTORS_FIELD_NUMBER: builtins.int
        UNMASK_VECTORS_FIELD_NUMBER: builtins.int
        @property
        def setup_param(self) -> global___ServerMessage.SecAggMsg.SetupParam: ...
        @property
        def ask_keys(self) -> global___ServerMessage.SecAggMsg.AskKeys: ...
        @property
        def share_keys(self) -> global___ServerMessage.SecAggMsg.ShareKeys: ...
        @property
        def ask_vectors(self) -> global___ServerMessage.SecAggMsg.AskVectors: ...
        @property
        def unmask_vectors(self) -> global___ServerMessage.SecAggMsg.UnmaskVectors: ...
        def __init__(
            self,
            *,
            setup_param: global___ServerMessage.SecAggMsg.SetupParam | None = ...,
            ask_keys: global___ServerMessage.SecAggMsg.AskKeys | None = ...,
            share_keys: global___ServerMessage.SecAggMsg.ShareKeys | None = ...,
            ask_vectors: global___ServerMessage.SecAggMsg.AskVectors | None = ...,
            unmask_vectors: global___ServerMessage.SecAggMsg.UnmaskVectors | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["ask_keys", b"ask_keys", "ask_vectors", b"ask_vectors", "msg", b"msg", "setup_param", b"setup_param", "share_keys", b"share_keys", "unmask_vectors", b"unmask_vectors"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["ask_keys", b"ask_keys", "ask_vectors", b"ask_vectors", "msg", b"msg", "setup_param", b"setup_param", "share_keys", b"share_keys", "unmask_vectors", b"unmask_vectors"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["msg", b"msg"]) -> typing_extensions.Literal["setup_param", "ask_keys", "share_keys", "ask_vectors", "unmask_vectors"] | None: ...

    RECONNECT_INS_FIELD_NUMBER: builtins.int
    GET_PROPERTIES_INS_FIELD_NUMBER: builtins.int
    GET_PARAMETERS_INS_FIELD_NUMBER: builtins.int
    FIT_INS_FIELD_NUMBER: builtins.int
    EVALUATE_INS_FIELD_NUMBER: builtins.int
    SEC_AGG_MSG_FIELD_NUMBER: builtins.int
    @property
    def reconnect_ins(self) -> global___ServerMessage.ReconnectIns: ...
    @property
    def get_properties_ins(self) -> global___ServerMessage.GetPropertiesIns: ...
    @property
    def get_parameters_ins(self) -> global___ServerMessage.GetParametersIns: ...
    @property
    def fit_ins(self) -> global___ServerMessage.FitIns: ...
    @property
    def evaluate_ins(self) -> global___ServerMessage.EvaluateIns: ...
    @property
    def sec_agg_msg(self) -> global___ServerMessage.SecAggMsg: ...
    def __init__(
        self,
        *,
        reconnect_ins: global___ServerMessage.ReconnectIns | None = ...,
        get_properties_ins: global___ServerMessage.GetPropertiesIns | None = ...,
        get_parameters_ins: global___ServerMessage.GetParametersIns | None = ...,
        fit_ins: global___ServerMessage.FitIns | None = ...,
        evaluate_ins: global___ServerMessage.EvaluateIns | None = ...,
        sec_agg_msg: global___ServerMessage.SecAggMsg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["evaluate_ins", b"evaluate_ins", "fit_ins", b"fit_ins", "get_parameters_ins", b"get_parameters_ins", "get_properties_ins", b"get_properties_ins", "msg", b"msg", "reconnect_ins", b"reconnect_ins", "sec_agg_msg", b"sec_agg_msg"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["evaluate_ins", b"evaluate_ins", "fit_ins", b"fit_ins", "get_parameters_ins", b"get_parameters_ins", "get_properties_ins", b"get_properties_ins", "msg", b"msg", "reconnect_ins", b"reconnect_ins", "sec_agg_msg", b"sec_agg_msg"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["msg", b"msg"]) -> typing_extensions.Literal["reconnect_ins", "get_properties_ins", "get_parameters_ins", "fit_ins", "evaluate_ins", "sec_agg_msg"] | None: ...

global___ServerMessage = ServerMessage

@typing_extensions.final
class ClientMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class DisconnectRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        REASON_FIELD_NUMBER: builtins.int
        reason: global___Reason.ValueType
        def __init__(
            self,
            *,
            reason: global___Reason.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["reason", b"reason"]) -> None: ...

    @typing_extensions.final
    class GetPropertiesRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class PropertiesEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        STATUS_FIELD_NUMBER: builtins.int
        PROPERTIES_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        @property
        def properties(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            status: global___Status | None = ...,
            properties: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["status", b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["properties", b"properties", "status", b"status"]) -> None: ...

    @typing_extensions.final
    class GetParametersRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATUS_FIELD_NUMBER: builtins.int
        PARAMETERS_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        @property
        def parameters(self) -> global___Parameters: ...
        def __init__(
            self,
            *,
            status: global___Status | None = ...,
            parameters: global___Parameters | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["parameters", b"parameters", "status", b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["parameters", b"parameters", "status", b"status"]) -> None: ...

    @typing_extensions.final
    class FitRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class MetricsEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        STATUS_FIELD_NUMBER: builtins.int
        PARAMETERS_FIELD_NUMBER: builtins.int
        NUM_EXAMPLES_FIELD_NUMBER: builtins.int
        METRICS_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        @property
        def parameters(self) -> global___Parameters: ...
        num_examples: builtins.int
        @property
        def metrics(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            status: global___Status | None = ...,
            parameters: global___Parameters | None = ...,
            num_examples: builtins.int = ...,
            metrics: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["parameters", b"parameters", "status", b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["metrics", b"metrics", "num_examples", b"num_examples", "parameters", b"parameters", "status", b"status"]) -> None: ...

    @typing_extensions.final
    class EvaluateRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class MetricsEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        STATUS_FIELD_NUMBER: builtins.int
        LOSS_FIELD_NUMBER: builtins.int
        NUM_EXAMPLES_FIELD_NUMBER: builtins.int
        METRICS_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        loss: builtins.float
        num_examples: builtins.int
        @property
        def metrics(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            status: global___Status | None = ...,
            loss: builtins.float = ...,
            num_examples: builtins.int = ...,
            metrics: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["status", b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["loss", b"loss", "metrics", b"metrics", "num_examples", b"num_examples", "status", b"status"]) -> None: ...

    @typing_extensions.final
    class SecAggRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class SetupParamRes(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            def __init__(
                self,
            ) -> None: ...

        @typing_extensions.final
        class AskKeysRes(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            PK1_FIELD_NUMBER: builtins.int
            PK2_FIELD_NUMBER: builtins.int
            SIGNATURE_FIELD_NUMBER: builtins.int
            SIG_PUB_FIELD_NUMBER: builtins.int
            pk1: builtins.bytes
            pk2: builtins.bytes
            signature: builtins.bytes
            sig_pub: builtins.bytes
            def __init__(
                self,
                *,
                pk1: builtins.bytes = ...,
                pk2: builtins.bytes = ...,
                signature: builtins.bytes = ...,
                sig_pub: builtins.bytes = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["pk1", b"pk1", "pk2", b"pk2", "sig_pub", b"sig_pub", "signature", b"signature"]) -> None: ...

        @typing_extensions.final
        class ShareKeysRes(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            @typing_extensions.final
            class Packet(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                SOURCE_FIELD_NUMBER: builtins.int
                DESTINATION_FIELD_NUMBER: builtins.int
                CIPHERTEXT_FIELD_NUMBER: builtins.int
                source: builtins.int
                destination: builtins.int
                ciphertext: builtins.bytes
                def __init__(
                    self,
                    *,
                    source: builtins.int = ...,
                    destination: builtins.int = ...,
                    ciphertext: builtins.bytes = ...,
                ) -> None: ...
                def ClearField(self, field_name: typing_extensions.Literal["ciphertext", b"ciphertext", "destination", b"destination", "source", b"source"]) -> None: ...

            PACKET_LIST_FIELD_NUMBER: builtins.int
            @property
            def packet_list(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ClientMessage.SecAggRes.ShareKeysRes.Packet]: ...
            def __init__(
                self,
                *,
                packet_list: collections.abc.Iterable[global___ClientMessage.SecAggRes.ShareKeysRes.Packet] | None = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["packet_list", b"packet_list"]) -> None: ...

        @typing_extensions.final
        class AskVectorsRes(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            PARAMETERS_FIELD_NUMBER: builtins.int
            @property
            def parameters(self) -> global___Parameters: ...
            def __init__(
                self,
                *,
                parameters: global___Parameters | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["parameters", b"parameters"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["parameters", b"parameters"]) -> None: ...

        @typing_extensions.final
        class UnmaskVectorsRes(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            @typing_extensions.final
            class ShareDictEntry(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                KEY_FIELD_NUMBER: builtins.int
                VALUE_FIELD_NUMBER: builtins.int
                key: builtins.int
                value: builtins.bytes
                def __init__(
                    self,
                    *,
                    key: builtins.int = ...,
                    value: builtins.bytes = ...,
                ) -> None: ...
                def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

            SHARE_DICT_FIELD_NUMBER: builtins.int
            @property
            def share_dict(self) -> google.protobuf.internal.containers.ScalarMap[builtins.int, builtins.bytes]: ...
            def __init__(
                self,
                *,
                share_dict: collections.abc.Mapping[builtins.int, builtins.bytes] | None = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["share_dict", b"share_dict"]) -> None: ...

        @typing_extensions.final
        class ErrorRes(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ERROR_FIELD_NUMBER: builtins.int
            error: builtins.str
            def __init__(
                self,
                *,
                error: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["error", b"error"]) -> None: ...

        SETUP_PARAM_RES_FIELD_NUMBER: builtins.int
        ASK_KEYS_RES_FIELD_NUMBER: builtins.int
        SHARE_KEYS_RES_FIELD_NUMBER: builtins.int
        ASK_VECTORS_RES_FIELD_NUMBER: builtins.int
        UNMASK_VECTORS_RES_FIELD_NUMBER: builtins.int
        ERROR_RES_FIELD_NUMBER: builtins.int
        @property
        def setup_param_res(self) -> global___ClientMessage.SecAggRes.SetupParamRes: ...
        @property
        def ask_keys_res(self) -> global___ClientMessage.SecAggRes.AskKeysRes: ...
        @property
        def share_keys_res(self) -> global___ClientMessage.SecAggRes.ShareKeysRes: ...
        @property
        def ask_vectors_res(self) -> global___ClientMessage.SecAggRes.AskVectorsRes: ...
        @property
        def unmask_vectors_res(self) -> global___ClientMessage.SecAggRes.UnmaskVectorsRes: ...
        @property
        def error_res(self) -> global___ClientMessage.SecAggRes.ErrorRes: ...
        def __init__(
            self,
            *,
            setup_param_res: global___ClientMessage.SecAggRes.SetupParamRes | None = ...,
            ask_keys_res: global___ClientMessage.SecAggRes.AskKeysRes | None = ...,
            share_keys_res: global___ClientMessage.SecAggRes.ShareKeysRes | None = ...,
            ask_vectors_res: global___ClientMessage.SecAggRes.AskVectorsRes | None = ...,
            unmask_vectors_res: global___ClientMessage.SecAggRes.UnmaskVectorsRes | None = ...,
            error_res: global___ClientMessage.SecAggRes.ErrorRes | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["ask_keys_res", b"ask_keys_res", "ask_vectors_res", b"ask_vectors_res", "error_res", b"error_res", "msg", b"msg", "setup_param_res", b"setup_param_res", "share_keys_res", b"share_keys_res", "unmask_vectors_res", b"unmask_vectors_res"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["ask_keys_res", b"ask_keys_res", "ask_vectors_res", b"ask_vectors_res", "error_res", b"error_res", "msg", b"msg", "setup_param_res", b"setup_param_res", "share_keys_res", b"share_keys_res", "unmask_vectors_res", b"unmask_vectors_res"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["msg", b"msg"]) -> typing_extensions.Literal["setup_param_res", "ask_keys_res", "share_keys_res", "ask_vectors_res", "unmask_vectors_res", "error_res"] | None: ...

    DISCONNECT_RES_FIELD_NUMBER: builtins.int
    GET_PROPERTIES_RES_FIELD_NUMBER: builtins.int
    GET_PARAMETERS_RES_FIELD_NUMBER: builtins.int
    FIT_RES_FIELD_NUMBER: builtins.int
    EVALUATE_RES_FIELD_NUMBER: builtins.int
    SEC_AGG_RES_FIELD_NUMBER: builtins.int
    @property
    def disconnect_res(self) -> global___ClientMessage.DisconnectRes: ...
    @property
    def get_properties_res(self) -> global___ClientMessage.GetPropertiesRes: ...
    @property
    def get_parameters_res(self) -> global___ClientMessage.GetParametersRes: ...
    @property
    def fit_res(self) -> global___ClientMessage.FitRes: ...
    @property
    def evaluate_res(self) -> global___ClientMessage.EvaluateRes: ...
    @property
    def sec_agg_res(self) -> global___ClientMessage.SecAggRes: ...
    def __init__(
        self,
        *,
        disconnect_res: global___ClientMessage.DisconnectRes | None = ...,
        get_properties_res: global___ClientMessage.GetPropertiesRes | None = ...,
        get_parameters_res: global___ClientMessage.GetParametersRes | None = ...,
        fit_res: global___ClientMessage.FitRes | None = ...,
        evaluate_res: global___ClientMessage.EvaluateRes | None = ...,
        sec_agg_res: global___ClientMessage.SecAggRes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["disconnect_res", b"disconnect_res", "evaluate_res", b"evaluate_res", "fit_res", b"fit_res", "get_parameters_res", b"get_parameters_res", "get_properties_res", b"get_properties_res", "msg", b"msg", "sec_agg_res", b"sec_agg_res"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["disconnect_res", b"disconnect_res", "evaluate_res", b"evaluate_res", "fit_res", b"fit_res", "get_parameters_res", b"get_parameters_res", "get_properties_res", b"get_properties_res", "msg", b"msg", "sec_agg_res", b"sec_agg_res"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["msg", b"msg"]) -> typing_extensions.Literal["disconnect_res", "get_properties_res", "get_parameters_res", "fit_res", "evaluate_res", "sec_agg_res"] | None: ...

global___ClientMessage = ClientMessage

@typing_extensions.final
class Scalar(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOUBLE_FIELD_NUMBER: builtins.int
    SINT64_FIELD_NUMBER: builtins.int
    BOOL_FIELD_NUMBER: builtins.int
    STRING_FIELD_NUMBER: builtins.int
    BYTES_FIELD_NUMBER: builtins.int
    double: builtins.float
    sint64: builtins.int
    """float float = 2;
    int32 int32 = 3;
    int64 int64 = 4;
    uint32 uint32 = 5;
    uint64 uint64 = 6;
    sint32 sint32 = 7;
    """
    bool: builtins.bool
    """fixed32 fixed32 = 9;
    fixed64 fixed64 = 10;
    sfixed32 sfixed32 = 11;
    sfixed64 sfixed64 = 12;
    """
    string: builtins.str
    bytes: builtins.bytes
    def __init__(
        self,
        *,
        double: builtins.float = ...,
        sint64: builtins.int = ...,
        bool: builtins.bool = ...,
        string: builtins.str = ...,
        bytes: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bool", b"bool", "bytes", b"bytes", "double", b"double", "scalar", b"scalar", "sint64", b"sint64", "string", b"string"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bool", b"bool", "bytes", b"bytes", "double", b"double", "scalar", b"scalar", "sint64", b"sint64", "string", b"string"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["scalar", b"scalar"]) -> typing_extensions.Literal["double", "sint64", "bool", "string", "bytes"] | None: ...

global___Scalar = Scalar
